name: pricing-speedboat
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20200225.2
  - adal=1.2.6
  - alabaster=0.7.12
  - appdirs=1.4.4
  - argon2-cffi=20.1.0
  - arrow-cpp=0.17.1
  - astroid=2.4.2
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=20.3.0
  - autopep8=1.5.4
  - aws-c-common=0.4.59
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.70
  - azure-common==1.1.26
  - azure-core==1.11.0
  - azure-datalake-store==0.0.49
  - azure-identity==1.5.0
  - azure-mgmt-core==1.2.2
  - azure-mgmt-storage==17.0.0
  - azure-storage-blob==12.7.1
  - azure-storage-file-datalake==12.2.3
  - babel=2.9.0
  - backcall=0.2.0
  - black=19.10b0
  - blas=1.0
  - bleach=3.3.0
  - blinker=1.4
  - blosc=1.20.1
  - boost-cpp=1.72.0
  - boruta_py=0.3
  - brotli=1.0.9
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cached-property=1.5.2
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=4.0.0
  - charls=2.1.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - cryptography=3.3.1
  - curl=7.71.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dash=1.17.0
  - dash-bootstrap-components=0.10.7
  - dash-core-components= 1.13.0
  - dask-core=2021.1.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - docutils=0.16
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - flask=1.1.2
  - flask-compress=1.8.0
  - freetype=2.10.4
  - future=0.18.2
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.4.0
  - grpc-cpp=1.33.2
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.10
  - imagecodecs=2020.5.30
  - imageio=2.9.0
  - imagesize=1.2.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2019.4
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - isodate=0.6.0
  - isort=4.3.21
  - itsdangerous=1.1.0
  - jdcal=1.4.1
  - jedi=0.18.0
  - jinja2=2.11.3
  - joblib=1.0.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.7.1
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.4.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - keyring=22.0.1
  - kiwisolver=1.3.0
  - krb5=1.18.2
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - libaec=1.0.4
  - libcurl=7.71.1
  - libevent=2.1.8
  - libgit2=1.0.1
  - libiconv=1.15
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libthrift=0.13.0
  - libtiff=4.1.0
  - libxml2=2.9.10
  - libxslt=1.1.34
  - libzopfli=1.0.3
  - lightgbm=2.3.0
  - lxml=4.6.2
  - lz4-c=1.9.2
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.0
  - more-itertools=8.6.0
  - msal=1.8.0
  - msal_extensions=0.3.0
  - msrest=0.6.19
  - msrestazure=0.6.2
  - msys2-conda-epoch=20160418
  - mypy=0.780
  - mypy_extensions=0.4.3
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.1
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nest-asyncio=1.4.3
  - networkx=2.2
  - notebook=6.2.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - oauthlib=3.1.0
  - olefile=0.46
  - openjpeg=2.3.0
  - openpyxl=3.0.3
  - openssl=1.1.1j
  - packaging=20.9
  - pandas=1.0.1
  - pandera=0.4.2
  - pandoc=2.11
  - pandocfilters=1.4.3
  - parquet-cpp=1.5.1
  - parso=0.8.1
  - pathspec=0.7.0
  - patsy=0.5.1
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=20.3.3
  - plotly=4.14.3
  - pluggy=0.13.1
  - pockets=0.9.1
  - portalocker=2.1.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - psutil=5.7.0
  - py=1.10.0
  - pyarrow=0.17.1
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pygit2=1.2.0
  - pygments=2.7.4
  - pyjwt=1.7.1
  - pylint=2.5.2
  - pyodbc=4.0.30
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytest=5.4.1
  - python=3.8.2
  - python-box=4.2.3
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pywavelets=1.1.1
  - pywin32=227
  - pywin32-ctypes=0.2.0
  - pywinpty=0.5.7
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - re2=2020.10.01
  - regex=2020.11.13
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - retrying=1.3.3
  - ruamel.yaml=0.16.12
  - ruamel.yaml.clib=0.2.2
  - scikit-image=0.17.2
  - scikit-learn=0.23.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=52.0.0
  - shap=0.34.0
  - sip=4.19.13
  - six=1.15.0
  - snappy=1.1.8
  - snowballstemmer=2.1.0
  - sphinx=3.0.3
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-napoleon=0.7
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlalchemy=1.3.19
  - sqlite=3.33.0
  - statsmodels=0.11.0
  - tabulate=0.8.7
  - terminado=0.9.2
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tifffile=2021.1.14
  - tk=8.6.7
  - toml=0.10.1
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.56.0
  - traitlets=5.0.5
  - typed-ast=1.4.2
  - typing_extensions=3.7.4.3
  - urllib3=1.26.3
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.11.2
  - xlrd=1.2.0
  - xlsxwriter=1.2.9
  - xz=5.2.5
  - yaml=0.1.7
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
      - dbutils==2.0