PIPELINE:
  run_id: 'test_run'
  write_proposals_to_db: False
  write_price_decreases_to_db: False
  write_proposals_to_disc: True
  write_price_decreases_to_disc: False
  path_outputs_root_folder: 'PATH_TO_SAVE_RUN_OUTPUT_FOLDERS_TO' # e.g. C:\\Users\\<USER>\\Documents\\price_proposal_output


DATA_MERGER:
  wg_manual_check_threshold: 0.9  # threshold for setting F_WG_MANUAL_CHECK_FLAG to TRUE
  sc_manual_check_threshold: 0.9  # threshold for setting F_SC_MANUAL_CHECK_FLAG to TRUE
  high_frequency_threshold: 1000  # threshold for setting F_HIGH_FREQUENCY_FLAG to TRUE
  high_price_threshold: 1000  # threshold for setting F_HIGH_PRICE_FLAG to TRUE
  high_value_at_risk_market_limit_perc: 0.00022 # percentage of total net revenue of a market above which TNR x market entry is considered high risk
  long_tail_revenue_threshold: 0.8 # percentage of revenue contributed by short tail, pareto values above are considered long tail
  chain_dimensions:
    - pred_succ
    - option_parts
  sps_mapping:
    '0': 'MB others'
    '1': 'Maintenance'
    '2': 'Wear & Tear'
    '3': 'Power train'
    '4': 'Elektric/Elektronic'
    '5': 'Heating/Air Condition'
    '6': 'Accident'
    '7': 'Interior'
    '9': 'Sonderwerkzeuge'

  MARKET_NAME_MAPPING:
    at: 'Austria'
    be: 'Belgium'
    ch: 'Switzerland'
    cz: 'Czech Republic'
    de: 'Germany'
    dk: 'Denmark'
    es: 'Spain'
    fr: 'France'
    gb: 'Great Britain'
    gr: 'Greece'
    it: 'Italy'
    nl: 'Netherlands'
    pl: 'Poland'
    pt: 'Portugal'
    ro: 'Romania'
    se: 'Sweden'

  manually_overwrite_elasticity: False

  MC_ID_LOW_CONFIDENCE_MANUAL:
    - '2LB010' # Engines, reman
    - '2LB026' # Manual transmissions, reman


IMPLEMENTATION_LEVER_SPLITTER:
  price_structure_price_increase_window: 0.2 # percentage differences between revenue weighted average and individual price increase suggestion are considered very different
  price_structure_revenue_inside_range_limit: 0.9 # percentage of revenue that needs to be in the price increase window to accept lever
  glp_price_increase_window: 0.25 # percentage differences between revenue weighted average and individual price increase suggestion are considered very different
  glp_revenue_inside_range_limit: 0.8 # percentage of revenue that needs to be in the price increase window to accept lever


PART_LEVEL_ADJUSTER:
  max_price_increase_for_high_avg_llp_increase_parts: 0.025 # minimum price reduction for parts that have a high avg. historic LLP increase
  max_price_increase_focus_parts: 0.015 # maximum price increase for focus parts
  high_volume_loss_threshold: -0.1 #currently dummy variable, limit below which avg. vol loss raises a warning flag
  reference_value_for_competitor_price_based_suggestion: 1 # target value for the competitor price level used for price level based price increases (1 mean same price level)
  above_100_LLP_avg_LLP_increase_limit: 0.025 # threshold for avg. historic LLP increase above which parts with LLP > 100 will have a price reduction
  below_100_LLP_avg_LLP_increase_limit: 0.04 # threshold for avg. historic LLP increase above which parts with LLP < 100 will have a price reduction


CUBE_LEVER_COMBINER:

  individual_proposal_price_move_sig_diff_threshold_perc: 0.25 # threshold above which the difference between individual proposal und final price move causes a warning
  competitor_price_level_threshold: 0.85 # threshold for the competitor price level after a price increase that causes a warning

  MARKET_PRICER_MAPPING:
    ro: 'Cansun Hekimoglu'
    pl: 'Cansun Hekimoglu'
    pt: 'Michael van Beers'
    be: 'Eduardo Amorosino'
    gb: 'Eduardo Amorosino'
    de: 'Klaus Rupp, Thomas Schroll'
    es: 'Katharina Dirian'
    it: 'Katharina Dirian'
    nl: 'Eduardo Amorosino'
    gr: 'Michael van Beers'
    ch: 'Katharina Dirian'
    at: 'Cansun Hekimoglu'
    cz: 'Cansun Hekimoglu'
    fr: 'Eduardo Amorosino'
    se: 'Michael van Beers'
    dk: 'Michael van Beers'

  WG_PRICER_MAPPING:
    '01': 'Klaus Rupp'
    '02': 'Klaus Rupp'
    '03': 'Klaus Rupp'
    '04': 'Klaus Rupp'
    '05': 'Thomas Schroll'
    '06': 'Thomas Schroll'
    '07': 'Thomas Schroll'
    '08': 'Thomas Schroll'
    '09': 'Eduardo Amorosino'
    '10': 'Klaus Rupp'
    '11': 'Thomas Schroll'
    '12': 'Thomas Schroll'
    '13': 'Thomas Schroll'
    '14': 'Thomas Schroll'
    '15': 'Thomas Schroll'
    '16': 'Katharina Dirian'
    '17': 'Klaus Rupp'
    '18': 'Klaus Rupp'
    '19': 'Klaus Rupp'
    '20': 'Cansun Hekimoglu'
    '21': 'Klaus Rupp'
    '22': 'Klaus Rupp'
    '23': 'Klaus Rupp'
    '24': 'Thomas Schroll'
    '25': 'Thomas Schroll'
    '26': 'Thomas Schroll'
    '28': 'Klaus Rupp'
    '29': 'Klaus Rupp'
    '30': 'Klaus Rupp'
    '31': 'Klaus Rupp'
    '34': 'Michael van Beers'
    '35': 'Katharina Dirian'
    '40': 'unknown'
    '41': 'Thomas Schroll'


PRICE_DECREASE_SUGGESTER:
  avg_rg_vol_loss_threshold_for_price_decrease: -0.25 # threshold for the avg. volume loss below which a price decrease is suggested
  price_decrease_margin_buffer: 0.2 # price decrease that should not result in a negative contribution margin
  low_competitor_price_limit_for_decrease_check: 0.9 # threshold below which the competitor price level as seen as a positive indicator for a price decrease


SEGMENTATION_BASED_PRICING_AMBITION:

  max_price_increase_focus_parts: 0.015 # maximum price increase for focus parts

  config_file_sheet_name: 'Segmentation'

  required_config_file_columns:
    - 'Bucket'
    - 'Price Elasticity'
    - 'Competitive index'
    - 'Long vs. Short Tail'
    - 'Market Share'
    - '0-10 Euro'
    - '100 Euro'
    - '250 Euro'
    - '500 Euro'
    - '750 Euro'
    - '1000 Euro'
    - '10000 Euro'


OUTPUT_WRITER:
  output_file_name_price_proposal_excel: 'price_proposal_output.xlsx'
  output_file_name_price_decreases_excel: 'price_decreases_output.xlsx'
  output_file_name_price_proposal_parquet: 'price_proposal_output.parquet'
  output_file_name_price_decreases_parquet: 'price_decreases_output.parquet'
  db_table_name_price_proposal: 'price_proposal'
  db_table_name_price_decreases: 'price_decreases'

